openapi: 3.0.1
info:
  title: Drive Proxy API
  version: "1.0.0"
  description: >
    Middleware entre GPT Builder e Google Drive.  
    Autenticação via Service Account.  
    **Sempre envie o header `x-api-key`.**
servers:
  - url: https://drive-proxy-juo9.vercel.app
paths:
  /api/search:
    get:
      summary: Buscar arquivos no Drive
      parameters:
        - name: query
          in: query
          schema:
            type: string
          description: Texto que deve aparecer no nome do arquivo.
        - name: folderId
          in: query
          schema:
            type: string
          description: ID da pasta do Drive para restringir a busca.
        - name: pageSize
          in: query
          schema:
            type: integer
            default: 10
          description: Quantidade de arquivos a retornar.
      responses:
        "200":
          description: Lista de arquivos encontrados.
  /api/export/{id}:
    get:
      summary: Exportar arquivo Google Docs/Sheets/Slides
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: mime
          in: query
          schema:
            type: string
            default: application/pdf
          description: Tipo MIME (ex. application/pdf, text/plain, text/csv).
      responses:
        "200":
          description: Conteúdo exportado em stream.
  /api/file/{id}:
    get:
      summary: Download de arquivo binário (PDF, imagem etc.)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Stream do arquivo binário.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
security:
  - ApiKeyAuth: []
